### ISSUE TITLE
Support JupyterLab

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/observable-jupyter-widget#3]
I have not yet opened JupyterLab to see if these work there. Since JupyterLab allows widgets to stick the side, bottom, etc. of the screen, how to we opt in into that?

**Comment by cornhundred** [comment]
I'm seeing the following error when I try to open the widget in JupyterLab

```
523.92b431af199caa12622d.js:1 Error: Module observable-jupyter-widget, semver range ^0.1.8 is not registered as a widget module
    at x.loadClass (523.92b431af199caa12622d.js:1:5727)
    at x.<anonymous> (272.eb0d340d1eec40ac564f.js:1:9479)
    at 272.eb0d340d1eec40ac564f.js:1:6081
    at Object.next (272.eb0d340d1eec40ac564f.js:1:6186)
    at 272.eb0d340d1eec40ac564f.js:1:5122
    at new Promise (<anonymous>)
    at D (272.eb0d340d1eec40ac564f.js:1:4867)
    at x.e._make_model (272.eb0d340d1eec40ac564f.js:1:9358)
    at x.<anonymous> (272.eb0d340d1eec40ac564f.js:1:9212)
    at 272.eb0d340d1eec40ac564f.js:1:6081
```

I'm thinking it might be related to this issue:
https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/39

Here's a link to a [Code Ocean capsule](https://codeocean.com/capsule/5548056/tree) that reproduces the issue - works in Jupyter Notebook and does not run in Jupyter Lab.

**Comment by thomasballinger** [comment]
I tried to get this up and running this morning and it's going to take more work, I can't make a release atm.

Thanks for reporting. The linked issue sounds plausible to me, but when I look at [the wheel](https://pypi.org/project/observable-jupyter-widget/) I do see both the lab extension and the nbextension in there (this is after downloading the wheel [here](https://pypi.org/project/observable-jupyter-widget/0.1.8.dev0/#files), unzipping it, and looking at the `observable_jupyter_widget-0.1.8.dev0.data/` directory)
<img width="431" alt="image" src="https://user-images.githubusercontent.com/458879/170313440-5a4291c8-255e-4db6-9dfc-efd05d045a61.png">

It is helpful to know that just publishing it at https://www.npmjs.com/package/observable-jupyter-widget may not be enough.

**Comment by cornhundred** [comment]
I raised an issue in the cookiecutter that I think you used to build this library @thomasballinger - let's see if we hear anything back :)
